language: java

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

env:
  - GWT_VERSION=2.6.1
  - GWT_VERSION=2.7.0
  - GWT_VERSION=2.8.0-SNAPSHOT

install: mvn verify clean --fail-never --quiet -DskipTests=true -Dinvoker.skip=true
script: mvn verify -Dinvoker.streamLogs=true -Dinvoker.mavenOpts="-Djava.net.preferIPv4Stack=true" -Dgwt.version=$GWT_VERSION

after_success:
  - ci/deploy-snapshot.sh

notifications:
  email: false

sudo: false
cache:
  directories:
    - $HOME/.m2
    - target/it-repo

