language: java

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

env:
  - GWT_VERSION=2.7.0
  - GWT_VERSION=2.8.0
  - GWT_VERSION=HEAD-SNAPSHOT

matrix:
  allow_failures:
    - jdk: oraclejdk7
      env: GWT_VERSION=HEAD-SNAPSHOT
    - jdk: openjdk7
      env: GWT_VERSION=HEAD-SNAPSHOT

install: true
script: mvn verify -Dinvoker.streamLogs=true -Dinvoker.mavenOpts="-Djava.net.preferIPv4Stack=true" -DgwtVersion=$GWT_VERSION

after_success:
  - ci/deploy-snapshot.sh

notifications:
  email: false

sudo: false
cache:
  directories:
    - $HOME/.m2
    - target/it-repo

