language: java

jdk:
  - openjdk7
  - openjdk8
  - oraclejdk10

env:
  - GWT_VERSION=2.8.2
  - GWT_VERSION=HEAD-SNAPSHOT

matrix:
  exclude:
    - jdk: openjdk7
      env: GWT_VERSION=HEAD-SNAPSHOT

install: true
script: mvn -U verify -Dinvoker.streamLogs=true -Dinvoker.mavenOpts="-Djava.net.preferIPv4Stack=true" -DgwtVersion=$GWT_VERSION

after_success:
  - ci/deploy-snapshot.sh

notifications:
  email: false

sudo: false
before_cache:
  - shopt -s globstar && rm -fr $HOME/.m2/**/*-SNAPSHOT/
  - shopt -s globstar && rm -fr target/it-repo/**/*-SNAPSHOT/
cache:
  directories:
    - $HOME/.m2
    - target/it-repo

